package crm

type RouterGroup struct {
	CrmTestRouter
	CrmContractTypeRouter
	CrmLoginLogRouter
	CrmOperationRecordsRouter
	CrmProcurementContractRouter
	CrmProductGroupRouter
	CrmProductTypeRouter
	CrmUserRouter
	CrmApprovalNodeRouter
	CrmApprovalProcessRouter
	CrmApprovalRecordRouter
	CrmApprovalTasksRouter
	CrmTicketCommentsRouter
	CrmTicketResponseTemplatesRouter
	CrmTicketsRouter
	CrmContactFileUploadAndDownloadsRouter
	CrmCustomerGroupRouter
	CrmCustomersRouter
	CrmProductRouter
	CrmBusinessOpportunityRouter
	CrmBillRouter
	CrmContractRouter
	CrmOrderRouter
	CrmPageCustomersRouter
	CrmPaymentRouter
	CrmPurchaseOrderRouter
	CrmStatementAccountRouter
	CrmSupplierRouter
	CrmCommissionRebateRouter
	CrmPageCommissionRebateRouter
	CrmPagePaymentRouter
	CrmPagePurchaseOrderRouter
	CrmPageStatementAccountRouter
	CrmPageSupplierRouter
	CrmPageProductRouter
	CrmPageBusinessOpportunityRouter
	CrmPageBillRouter
	CrmPageContractRouter
	CrmPageOrderRouter

	CrmPagePaymentCollentionRouter
	CrmPaymentCollentionRouter
}
