package crm

type RouterGroup struct {
	CrmTestRouter
	CrmBillRouter
	CrmBusinessOpportunityRouter
	CrmCommissionRebateRouter
	CrmContractRouter
	CrmContractTypeRouter
	CrmCustomersRouter
	CrmLoginLogRouter
	CrmOperationRecordsRouter
	CrmOrderRouter
	CrmPaymentRouter
	CrmPaymentCollentionRouter
	CrmProcurementContractRouter
	CrmProductRouter
	CrmProductGroupRouter
	CrmProductTypeRouter
	CrmPurchaseOrderRouter
	CrmStatementAccountRouter
	CrmSupplierRouter
	CrmUserRouter
	CrmApprovalNodeRouter
	CrmApprovalProcessRouter
	CrmApprovalRecordRouter
	CrmApprovalTasksRouter
	CrmTicketCommentsRouter
	CrmTicketResponseTemplatesRouter
	CrmTicketsRouter
}
