package crm

type RouterGroup struct {
	CrmTestRouter
	CrmCommissionRebateRouter
	CrmContractTypeRouter
	CrmLoginLogRouter
	CrmOperationRecordsRouter
	CrmPaymentRouter
	CrmProcurementContractRouter
	CrmProductGroupRouter
	CrmProductTypeRouter
	CrmPurchaseOrderRouter
	CrmStatementAccountRouter
	CrmSupplierRouter
	CrmUserRouter
	CrmApprovalNodeRouter
	CrmApprovalProcessRouter
	CrmApprovalRecordRouter
	CrmApprovalTasksRouter
	CrmTicketCommentsRouter
	CrmTicketResponseTemplatesRouter
	CrmTicketsRouter
	CrmContactFileUploadAndDownloadsRouter
	CrmCustomerGroupRouter
	CrmCustomersRouter
	CrmProductRouter
	CrmBusinessOpportunityRouter
	CrmBillRouter
	CrmContractRouter
	CrmOrderRouter
	CrmPaymentCollentionRouter
	CrmPageCustomersRouter
}
