package crm

type ServiceGroup struct {
	CrmTestService
	CrmCommissionRebateService
	CrmContractTypeService
	CrmLoginLogService
	CrmOperationRecordsService
	CrmPaymentService
	CrmProcurementContractService
	CrmProductGroupService
	CrmProductTypeService
	CrmPurchaseOrderService
	CrmStatementAccountService
	CrmSupplierService
	CrmUserService
	CrmApprovalNodeService
	CrmApprovalProcessService
	CrmApprovalRecordService
	CrmApprovalTasksService
	CrmTicketCommentsService
	CrmTicketResponseTemplatesService
	CrmTicketsService
	CrmContactFileUploadAndDownloadsService
	CrmCustomerGroupService
	CrmCustomersService
	CrmProductService
	CrmBusinessOpportunityService
	CrmBillService
	CrmContractService
	CrmOrderService
	CrmPaymentCollentionService
}
