package crm

type ServiceGroup struct {
	CrmTestService
	CrmBillService
	CrmBusinessOpportunityService
	CrmCommissionRebateService
	CrmContractService
	CrmContractTypeService
	CrmCustomersService
	CrmLoginLogService
	CrmOperationRecordsService
	CrmOrderService
	CrmPaymentService
	CrmPaymentCollentionService
	CrmProcurementContractService
	CrmProductService
	CrmProductGroupService
	CrmProductTypeService
	CrmPurchaseOrderService
	CrmStatementAccountService
	CrmSupplierService
	CrmUserService
	CrmApprovalNodeService
	CrmApprovalProcessService
	CrmApprovalRecordService
	CrmApprovalTasksService
	CrmTicketCommentsService
	CrmTicketResponseTemplatesService
	CrmTicketsService
}
