package crm

type ServiceGroup struct {
	CrmTestService
	CrmContractTypeService
	CrmLoginLogService
	CrmOperationRecordsService
	CrmProcurementContractService
	CrmProductGroupService
	CrmProductTypeService
	CrmUserService
	CrmApprovalNodeService
	CrmApprovalProcessService
	CrmApprovalRecordService
	CrmApprovalTasksService
	CrmTicketCommentsService
	CrmTicketResponseTemplatesService
	CrmTicketsService
	CrmContactFileUploadAndDownloadsService
	CrmCustomerGroupService
	CrmCustomersService
	CrmProductService
	CrmBusinessOpportunityService
	CrmBillService
	CrmContractService
	CrmOrderService
	CrmPaymentService
	CrmPurchaseOrderService
	CrmStatementAccountService
	CrmSupplierService
	CrmCommissionRebateService
	CrmPaymentCollentionService
}
