name: Deploy Go App

on:
  push:
    branches: [ main ]  # 触发条件：当有代码被推送到 main 分支时
    paths:             # 只有 server 文件夹下的文件发生变化时才触发
      - 'server/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # 您的 Go 版本可能不同，请根据实际情况调整

    - name: Build
      working-directory: ./server  # 指定工作目录
      run: |
        go mod download
        go build -o server .

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 110.41.190.242  # 替换为您的服务器主机名或 IP 地址
        username: root           # 替换为您的服务器用户名
        password: jyy88888888           # 替换为您的服务器密码
        port: 22                 # 替换为您的 SSH 端口号，默认为 22
        timeout: 15m                      # 增加超时时间为 15 分钟
        script: |
          echo "Starting deployment script..."
          # 在服务器上停止旧的应用程序
          pkill -f "/www/goserve/server"
          # 清除旧的二进制文件
          rm -rf /www/goserve/*
          # 创建目录
          #mkdir -p /www/goserve
          # 上传新编译的二进制文件
          scp -P your-port ./server your-username@your-server-hostname-or-ip:/www/goserve/server
          # 启动新应用程序
          nohup /www/goserve/server &
          echo "Deployment script completed."